[package]
name = "Suimart"
version = "0.0.1"
authors = ["Suimart Contributors"]

[addresses]
suimart = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework", rev = "main" }